server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    jsp:
      init-parameters:
        development: true  # JSP 개발 모드

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0  # 개발 시 캐시 비활성화

  datasource:
    url: ${DB_URL:jdbc:mysql://3.39.50.163:3306/bidon_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      # 연결 실패 시 재시도
      validation-timeout: 5000
      leak-detection-threshold: 60000

  # 기존 JPA 설정
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  jpa:
    hibernate:
      ddl-auto: validate  # 스키마 자동변경 설정. 개발시에는 update 추천
    show-sql: false        # 개발시에는 true : SQL 쿼리를 로그에 보여줌
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss



file:
  upload-dir: "C:\\20240801-gangnam\\Project\\img"  # Windows 경로 수정
  base-url: "http://112.221.66.174:8080/images/"

# 로깅 설정 (JSP 개발 시 유용)
logging:
  level:
    com.cloud.auction_back: DEBUG
    org.springframework.web: INFO
