server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    jsp:
      init-parameters:
        development: true  # JSP 개발 모드
  forward-headers-strategy: native # 프록시 헤더 처리

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0  # 개발 시 캐시 비활성화
      # period: 86400  # 프로덕션에서는 캐시 활성화 (24시간)

  datasource:
    url: ${DB_URL:jdbc:mysql://bod-db-at.cpe0ugu20lct.ap-northeast-2.rds.amazonaws.com:3306/bidon_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
      # 연결 실패 시 재시도
      validation-timeout: 5000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: create  # 스키마 자동변경 설정. 개발시에는 update 추천
    show-sql: true        # 개발시에는 true : SQL 쿼리를 로그에 보여줌
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
          batch_size: 20
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
    open-in-view: false  # 성능 최적화

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

# MyBatis 설정 추가
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cloud.cloudproject.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: reuse
    default-statement-timeout: 25000

# 파일 업로드 경로를 Linux 경로로 변경
file:
  upload-dir: "/usr/local/tomcat/uploads"
  base-url: "${BASE_URL:http://localhost:8080}/images/"
  max-size: 10MB

# 로깅 설정 강화
logging:
  level:
    root: INFO
    com.cloud.cloudproject: DEBUG
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /usr/local/tomcat/logs/spring-boot.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: db,ping
        liveness:
          include: ping,diskSpace
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    db:
      enabled: true
      diskspace:
        enabled: true
        threshold: 100MB
  server:
    port: 8080
