server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    jsp:
      init-parameters:
        development: true  # JSP 개발 모드

spring:
  # JSP 뷰 리졸버 설정 추가
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  # 정적 리소스 설정 추가  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0  # 개발 시 캐시 비활성화
  
  # 기존 데이터베이스 설정 유지
  datasource:
    url: jdbc:mysql://3.39.50.163:3306/bidon_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: powermvp
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 기존 JPA 설정 유지
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  jpa:
    hibernate:
      ddl-auto: update   # 스키마 자동변경 설정. 실운영시에는 validate 추천
    show-sql: true        # SQL 쿼리를 로그에 보여줌
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # 기존 Jackson 설정 유지
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

# 기존 MyBatis 설정 유지 (필요시)
mybatis:
  mapper-locations: mapper/*.xml


# 기존 파일 업로드 설정 유지
file:
  upload-dir: "C:\\20240801-gangnam\\Project\\img"  # Windows 경로 수정
  base-url: "http://112.221.66.174:8080/images/"

# 로깅 설정 (JSP 개발 시 유용)
logging:
  level:
    com.cloud.auction_back: DEBUG
    org.springframework.web: INFO
