apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream springboot-backend {
        server springboot-service:8080;
        keepalive 32;
    }
    
    server {
        listen 80;
        server_name _;
    
        # 타임아웃 설정
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        send_timeout 300s;
    
        # 클라이언트 요청 크기 제한
        client_max_body_size 50M;
    
        location / {
            proxy_pass http://springboot-backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection "";
            proxy_http_version 1.1;
            proxy_redirect off;
    
            # 추가 버퍼링 설정
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
        }
    
        # 헬스체크용 엔드포인트
        location /actuator/health {
            proxy_pass http://springboot-backend/actuator/health;
            proxy_set_header Host $host;
            access_log off;
        }
    
        # 에러 페이지 설정
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
