apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      # 초기화 컨테이너로 Spring Boot 서비스 대기
      initContainers:
        - name: wait-for-springboot
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nslookup springboot-service.default.svc.cluster.local; do
                echo "Waiting for springboot-service..."
                sleep 2
              done
              echo "springboot-service is available"
      containers:
        - name: nginx
          image: your-registry/nginx-custom:latest  # 커스텀 이미지
          ports:
            - containerPort: 80
          # 헬스체크 개선
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3