apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidonproject-springboot
  namespace: bidon-proj-ns
  labels:
    type: bidonproject-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bidonproject-springboot
  template:
    metadata:
      labels:
        app: bidonproject-springboot
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: bidonproject-springboot
      nodeSelector:
        role: workers
      containers:
        - name: bidonproject-springboot
          image: 679835924866.dkr.ecr.ap-northeast-2.amazonaws.com/bidon/spring:v1.4
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:mysql://bod-db-at.cpe0ugu20lct.ap-northeast-2.rds.amazonaws.com:3306/bidon_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: bidonproject-springboot-service
  namespace: bidon-proj-ns
spec:
  selector:
    app: bidonproject-springboot
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
