apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      nodeSelector:
        role: workers
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c']
          args:
            - |
              echo "Checking MySQL connectivity..."
              until nc -z 3.39.50.163 3306; do
                echo "MySQL not ready, waiting..."
                sleep 2
              done
              echo "MySQL is ready!"
      containers:
        - name: springboot-app
          image: 738404842710.dkr.ecr.ap-northeast-2.amazonaws.com/bidon:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:mysql://3.39.50.163:3306/bidon_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
