apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-hpa
  namespace: bidon-proj-ns
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bidonproject-springboot
  targetCPUUtilizationPercentage: 40