# argo-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Argo CD UI에 표시될 애플리케이션 이름
  name: cloud-project-argoCD
  # Argo CD가 설치된 네임스페이스
  namespace: argoCD
spec:
  project: default
  source:
    # 1단계에서 만든 Manifest 리포지토리 주소
    repoURL: 'https://github.com/won24/cloud-project-manifests.git'
    # 감시할 브랜치
    targetRevision: HEAD
    # YAML 파일들이 있는 경로
    path: k8s
  destination:
    # 배포할 대상 클러스터 (클러스터 내부를 의미)
    server: 'https://kubernetes.default.svc'
    # 배포할 네임스페이스
    namespace: bidon-proj-ns
  # 동기화 정책 설정
  syncPolicy:
    automated:
      prune: true    # Git에서 사라진 리소스는 클러스터에서도 자동 삭제
      selfHeal: true # 클러스터 상태가 Git과 다르면 자동으로 Git 상태로 복구
    syncOptions:
      - CreateNamespace=true # 'bidon-proj-ns' 네임스페이스가 없으면 자동 생성